#goal definition
string objective_id
diagnostic_msgs/KeyValue[] qos_expected
---
#result definition
std_msgs/Empty result
---
#feedback definition
std_msgs/Bool reconfigure_needed
diagnostic_msgs/KeyValue[] qos_status