#goal definition
geometry_msgs/PoseStamped pose
string behavior_tree
diagnostic_msgs/KeyValue[] qos_expected
---
#result definition
std_msgs/Empty result
---
#feedback definition
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
int16 number_of_recoveries
float32 distance_remaining
diagnostic_msgs/KeyValue[] qos_status